# fly.toml app configuration file generated for tasklist-young-snow-5136 on 2025-06-06T16:10:38+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tasklist-young-snow-5136'
primary_region = 'nrt'

[build]
  dockerfile = './docker/8.3/Dockerfile'

[env]
  APP_DEBUG = 'false'
  APP_NAME = 'Laravel'
  APP_URL = 'https://tasklist-bold-wave-5657.fly.dev'
  DATABASE_URL = 'postgresql://postgres.mobxmhafxtxhbbiylpdi:o6bsOQWIO27ggUYP@aws-0-ap-northeast-1.pooler.supabase.com:5432/postgres'
  DB_CONNECTION = 'pgsql'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
